[tool.poetry]
name = "rdptools"
version = "0.1.7"
description = ""
authors = ["Baiyue Cao <caobaiyue@live.com>"]

[tool.poetry.dependencies]
python = "3.*"
office365-rest-client = "2.2.0"
pandas = "*"
geopandas = "*"
python-dotenv = "^0.14.0"