name: BetaNYC Runner
on:
  repository_dispatch:
    types: [betanyc]
  schedule:
    - cron: 0 0 */3 * *

jobs:
  build:
    runs-on: self-hosted
    container: nycplanning/rdp:latest
    env:
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set Up
        shell: bash
        run: |
          ./rdp setup
          mkdir -p ~/.ssh
          mc cp spaces/recovery-data-partnership/utils/id_rsa ~/.ssh/id_rsa_axway
          mc cp spaces/recovery-data-partnership/utils/.env .env
          chmod 600 ~/.ssh/id_rsa_axway

      - name: Run recipes
        shell: bash
        run: |
          ./rdp run recipe betanyc
      
      - name: Clean up
        shell: bash
        run: |
          rm ~/.ssh/id_rsa_axway
          rm .env
          rm -rf recipes/betanyc/output
          rm -rf recipes/betanyc/input
      
