name: BetaNYC Runner
on:
  repository_dispatch:
    types: [betanyc]
  schedule:
    - cron: 0 0 */3 * *

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set Up
        shell: bash
        run: |
          ./rdp setup
          mkdir -p ~/.ssh
          mc cp spaces/recovery-data-partnership/utils/id_rsa ~/.ssh/id_rsa_axway
          mc cp spaces/recovery-data-partnership/utils/.env .env
          chmod 600 ~/.ssh/id_rsa_axway

      - name: Run recipes
        shell: bash
        run: ./rdp axway ls -l
      
      - name: destroy
        shell: bash
        run: |
          rm ~/.ssh/id_rsa_axway
          rm .env
      
