name: BetaNYC Runner
on:
  repository_dispatch:
    types: [betanyc]
  schedule:
    - cron: 0 0 */3 * *

jobs:
  build:
    runs-on: self-hosted
    env:
      RDP_DATA: ${{ secrets.PROD_RDP_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AXWAY_USER: ${{ secrets.AXWAY_USER }}
      AXWAY_HOST: ${{ secrets.PROD_AXWAY_HOST }}
    steps:
      - uses: actions/checkout@v2

      - name: Set Up
        shell: bash
        run: |
          ./rdp setup
          mkdir -p ~/.ssh
          mc cp spaces/recovery-data-partnership/utils/id_rsa ~/.ssh/id_rsa_axway
          chmod 600 ~/.ssh/id_rsa_axway

      - name: Run recipes
        shell: bash
        run: ./rdp axway ls -l
