name: publish-pypi

on:
  push:
    branches:
      - rdptools
      - master
    paths:
      - 'rdptools/*'
      - '.github/workflows/pypi.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Publish Python Package
      uses: mariamrf/py-package-publish-action@v1.0.0
      with:
        python_version: '3.7.0'
        subdir: rdptools
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
